spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/fiscaliza_db
        username: postgres
        password: 1234
        name: fiscaliza_db
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    h2:
        console:
            enabled: true