server:
    port: 8090
       
#List of trusted client credentials
oauth2:
    resource-server:
        client-id: resource-server
        client-secret: '123'
    angular:
        client-id: client
        client-secret: '123'

#Authserver root address
    authorization-server-address:  http://auth-server:8090

# Change when ready to production
spring:
    profiles:
        active: dev

debug: true

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: trace