server:
    port: 8090

spring:
    # jpa:
    #     defer-datasource-initialization: true
    # Change when ready to production
    profiles:
        active: prod
    
oauth2:
    #Authserver root address
    authorization-server-address:  http://auth-server:8090
    #List of trusted client credentials
    angular:
        client-id: agent-client
        client-secret: '123'
    ionic:
        client-id: user-client
        client-secret: '123'

# debug: true

# logging:
#   level:
#     root: DEBUG
#     org:
#       springframework:
#         security: trace