server:
    port: 8090

#debug: true

logging:
    level:
        root: DEBUG
        org:
            springframework:
                security: trace
spring:
    # jpa:
    #     defer-datasource-initialization: true
    # Change when ready to production
    profiles:
        active: dev
    
oauth2:
    #Authserver root address
    authorization-server-address:  http://auth-server:8090
    #List of trusted client credentials
    client1:
        client-id: agent-client
        client-secret: '123'
        redirect-uri: http://127.0.0.1:8100/redirection # Agent client home page
        cors-allowed-origin: http://127.0.0.1:8100
    client2:
        client-id: citizen-client 
        client-secret: '123'
        redirect-uri: http://127.0.0.1:8100/redirection # Citizen client redirection page
        cors-allowed-origin: '*'
    resource:
        client-id: resource-client
        client-secret: '123'
