spring:
    datasource:
        url: jdbc:h2:file:../test_db/fiscaliza_db;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=8000; # In mixed mode, the url must be equal to host application
        username: sa
        password:
        name: fiscaliza_db
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        #generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none
