server:
    port: 8090

spring:
    # jpa:
    #     defer-datasource-initialization: true
    # Change when ready to production
    profiles:
        active: dev
    
oauth2:
    #Authserver root address
    authorization-server-address:  http://auth-server:8090
    #List of trusted client credentials
    resource-server:
        client-id: resource-server
        client-secret: '123'
    angular:
        client-id: client
        client-secret: '123'

debug: true

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: trace