#This is application is responsable to host h2 database
spring:
    datasource:
        url: jdbc:h2:file:../test_db/fiscaliza_db;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=8000; # Sets h2 in mixed mode ( embedded + server )
        username: sa
        password:
        name: fiscaliza_db
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create-drop # update # create-drop
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
            path: /h2
