spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://auth-server:8090
                    jwk-set-uri: http://auth-server:8090/oauth2/jwks
            client:
              registration:
                authz-server:
                    client-id: resource-client
                    client-secret: '123'
                    scope: admin, agent, user
              provider:
                authz-server:
                    issuer-uri: http://auth-server:8090
                    introspect: http://auth-server:8090/oauth2/introspect
    profiles:
        active: dev # Change when ready to production
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
            location: ../images

cors:
    allowed-origins: >
        http://127.0.0.1:4200,
        http://127.0.0.1:8100,
        *
        
debug: true

logging:
  level:
    root: DEBUG
    org:
      springframework:
        security: trace
