spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://auh-server:8090
    profiles:
        active: prod # Change when ready to production

        

cors:
    allowed-origins: >
        http://127.0.0.1:4200,
        *
        
#debug: true

#logging:
  #level:
    #root: DEBUG
    #org:
      #springframework:
        #security: trace
