spring:
    datasource:
        url: jdbc:h2:tcp://localhost:8000/../test_db/fiscaliza_db
        username: sa
        password:
        name: fiscaliza_db
        driver-class-name: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        hibernate:
            ddl-auto: create
    h2:
        console:
            enabled: true