spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://auh-server:8090
    profiles:
        active: dev # Change when ready to production