server:
    port: 8090
       
#List of trusted client credentials
oauth2:
    resource-server:
        client-id: resource-server
        client-secret: '123'
    angular:
        client-id: client-server
        client-secret: '123'

#Authserver root address
    authorization-server-address:  http://auth-server:8090

# Change when ready to production
spring:
    profiles:
        active: dev